-- use book_rentel_system;
-- show tables;

-- desc book_category;
-- ALTER TABLE user_reg
-- MODIFY COLUMN user_id varchar(255) not null;
-- use bookrentelsystem;
-- desc book;
-- select * from book where category='None';
-- desc cart;
-- select*from user_reg;
-- select*from book;
-- select*from user_file;
-- delete from user_reg where user_email='sajal@gmail.com';
-- create database BookRentelSystem;
-- create database SecondStoryBookStore;
use SecondStoryBookStore;
-- desc validate_return_date;
-- SELECT * FROM books;
-- show tables;
-- select*from return_order;
-- ALTER TABLE orders ADD subtotal int;
-- select*from Book_category;
-- desc books;
-- ALTER TABLE books ADD FOREIGN KEY (category) REFERENCES book_category(category);
-- select sku, from books where category='English';
-- alter table books MODIFY COLUMN category varchar(255) not null;
-- select title from books where 'category'='Novel';
-- desc validate_return_date;
-- select*from return_order;
-- select* from validate_return_date;
-- delete from books where sku='Novel-3';
-- ALTER TABLE orders ADD review text;
-- delete from orders where order_id='6585bc81cb834';

-- create table validate_return_date(
--     user_id varchar(255) not null,
--     return_date date not null
-- );
desc return_order;
-- create table cart(
--     id varchar(255) not null,
--     sku varchar(255) not null,
--     FOREIGN KEY (id) REFERENCES user_registration(id),
--     FOREIGN KEY (sku) REFERENCES books(sku)
-- )
-- select* from cart;
-- ALTER TABLE cart DROP email;
-- show tables;
-- desc books;
-- desc user_registration;
-- ALTER TABLE admin
-- MODIFY COLUMN id varchar(255);
-- select*from books; 
-- select*from books_price; 

-- delete from books where sku='Novel-3';
-- select*from books_price;  

-- delete from book_category where category=null;

-- delete from admin where email='sajal@gmail.com';
-- desc user_registration
-- create table user_registration(
--     id varchar(255) not null,
--     email varchar(255) not null,
--     phone varchar(10) not null,
--     name varchar(255) not null,
--     gender varchar(20) not null,
--     dob date not null,
--     address varchar(255) not null,   
--     security_question varchar(255) not null,
--     password varchar(255) not null,
--     status varchar(20) not null,
--     registration_date date not null,
--     modified_date date not null,
--     profile_picture varchar(255),
--     PRIMARY KEY(id)
-- );

-- desc user_registration;
-- select*from user_registration;
-- delete from user_registration where email="jyoti@gmail.com";
-- create table super_admin(     
--     id int not null,
--     email varchar(255) not null,
--     phone varchar(10) not null,
--     name varchar(255) not null,
--     gender varchar(20) not null,
--     dob date not null,
--     address text not null,   
--     password varchar(255) not null,
--     profile_picture varchar(255),
--     admin_created date not null,
--     admin_modified date not null,    
--     PRIMARY KEY(id)
-- );
-- desc super_admin;
-- show tables;

-- create table admin(     
--     id int not null,
--     email varchar(255) not null,
--     phone varchar(10) not null,
--     name varchar(255) not null,
--     gender varchar(20) not null,
--     dob date not null,
--     address text not null,   
--     password varchar(255) not null,
--     profile_picture varchar(255),
--     admin_created date not null,
--     admin_modified date not null,
--     PRIMARY KEY(id)
-- );
-- desc admin;
-- drop table super_admin;
-- desc super_admin;
-- insert into super_admin(id, email, phone, name, gender, dob, address, password, profile_picture, admin_created, admin_modified) values(1,'paramjeetkaur@gmail.com', 7973276717,'Paramjeet Kaur','female','2002-10-07','chandigarh', 'Param@161607','super.jpg',now(),now());
-- select*from super_admin;
-- delete from super_admin where s_admin_email="paramjeetkaur@gmail.com";
-- ALTER TABLE super_admin MODIFY COLUMN s_admin_password varchar(255) not null;
-- select*from admin where admin_email='neeraj@gmail.com' or admin_id='65704f70895ca';
-- insert into super_admin values(1,'paramjeetkaur@gmail.com','7973276717','Paramjeet Kaur','female','2002-10-07','#param,chandigarh','Param@161607','super_admin.jpg',now(),now());
-- select*from super_admin;
-- show tables;
-- delete from user_file where user_email="sajal@gmail.com";
-- desc user_reg;
-- desc user_file;
-- desc book_category;
-- insert into book_category(category) values("hindi");
-- select*from book_category;
-- delete FROM book_category where category="english";
-- select*from user_reg;
-- select*from user_file;
-- delete from user_reg where user_name="param";
-- create table user_file(
--     user_email varchar(255) not null,
--     user_image varchar(255) not null,
--     user_image_path varchar(255) not null,
--     user_image_uniqe_id varchar(255) not null,
--     FOREIGN KEY (user_email) REFERENCES user_reg(user_email)
-- );

-- alter table user_file MODIFY COLUMN user_image_uniqe_id varchar(255);
-- select*from super_admin;
-- desc super_admin;
-- ALTER TABLE super_admin ADD COLUMN s_admin_created DATE NOT NULL;
-- ALTER TABLE super_admin ADD s_admin_created date not null;
-- alter table super_admin MODIFY COLUMN s_admin_image varchar(255);
-- alter table super_admin DROP COLUMN s_admin_id;

-- ALTER TABLE user_file
-- ADD FOREIGN KEY (user_email) REFERENCES user_reg(user_email);
-- delete from user_reg where user_email="sajal@gmail.com";
-- delete from user_file where user_email="sajal@gmail.com";
-- show tables;
-- -- desc book_category;
-- create table book_category(
--     category varchar(255) not null,
--     PRIMARY KEY(category)
-- );
-- drop table book_category;
-- ALTER TABLE book 
-- ADD CONSTRAINT category
-- FOREIGN KEY(book_category) 
-- REFERENCES book_category(category);
-- desc books;
-- drop table book;
-- create table books(
--     id varchar(255) NOT NULL,
--     sku varchar(20) NOT NULL,
--     title varchar(50) NOT NULL,
--     author varchar(50) NOT NULL,
--     category varchar(255) NOT NULL,
--     discription text NOT NULL,
--     quantity int NOT NULL,
--     cover_image varchar(255) NOT NULL,
--     book_uploaded date not null,
--     book_modified date not null,
--     PRIMARY KEY(sku)
-- );
-- drop table books;
-- create table books_price(
--     sku varchar(20) NOT NULL,
--     mrp int NOT NULL,
--     per_day_price int NOT NULL,
--     FOREIGN KEY (sku) REFERENCES books(sku)
-- );
-- show tables;
-- ALTER TABLE book MODIFY COLUMN book_desc text NOT NULL;
-- drop table book;
-- show tables;
-- desc user_file;
-- create table book_file(
--     book_sku varchar(20) NOT NULL,
--     book_image varchar(255) NOT NULL,
--     book_path varchar(255) NOT NULL,
--     book_unique varchar(255) NOT NULL,
--     FOREIGN KEY (book_sku) REFERENCES book(book_sku)
-- );
-- show tables;
-- desc book_file;
-- ALTER TABLE book add book_unique_id varchar(255) NOT NULL;
-- select*from user_reg;
-- SELECT COUNT(book_sku) FROM book;
-- -- select*from book;
-- drop table book_category;
-- alter table book_category DROP COLUMN category_image;

-- select*from user_reg;

-- create table cart(
--  user_email varchar(255) not null,
--  book_sku varchar(255) not null 
-- );
-- desc cart;
-- select*from cart;
-- delete from cart where book_sku='romance-1';
-- drop table cart;

-- SELECT book_sku FROM cart where user_email='sajal@gmail.com';
-- create table orders(
--     order_id varchar(255) not null,
--     user_id varchar(255) not null,
--     customer_name varchar(255) not null,
--     customer_phone int(10) not null,
--     customer_address text not null,
--     sku varchar(255) not null,
--     order_date date not null,
--     return_date date not null,
--     payment varchar(255) not null,
--     Note text,
--     PRIMARY KEY(order_id)    
-- );
-- alter table admin MODIFY COLUMN admin_id varchar(255);
-- select*from orders;
-- -- drop table orders;
-- delete from orders where customer_email="sajal@gmail.com";
-- delete from return_order where customer_email="sajal@gmail.com";

-- create table return_order(
--     user_id varchar(255) not null,    
--     sku varchar(255) not null,
--     order_date date not null,
--     return_date date not null,
--     review text 
-- );
-- desc user_file;
-- select*from user_reg;
-- select*from user_file;

-- alter table orders add order_id varchar(255) not null;
-- select*from return_order;
-- select*from orders;
-- SELECT * FROM book LEFT JOIN orders ON book.book_sku=orders.book_sku LEFT JOIN return_order ON book.book_sku=return_order.book_sku WHERE return_order.book_sku='POETRY-1';
-- delete from user_reg where user_email='sajal@gmail.com';
-- delete from user_file where user_email='sajal@gmail.com';
-- alter table user_file MODIFY COLUMN user_image_uniqe_id varchar(255);
-- select*from super_admin



